import type { DecisionTree } from './types';

export const decisionTree: DecisionTree = {
  start: 'Q0',
  nodes: {
    Q0: {
      id: 'Q0',
      type: 'question',
      questionText: 'Pick the highest rotation order you can prove (or select none).',
      note: 'Put the corner of your unit cell at equivalent rotation points.',
      answers: [
        { key: 'none', label: 'No rotations to prove', next: 'QNR_MIRRORS' },
        { key: 'rot2', label: '2-fold (180°)', next: 'Q2', proofType: 'rotation', rotationAngleDeg: 180 },
        { key: 'rot3', label: '3-fold (120°)', next: 'Q3', proofType: 'rotation', rotationAngleDeg: 120 },
        { key: 'rot4', label: '4-fold (90°)', next: 'Q4', proofType: 'rotation', rotationAngleDeg: 90 },
        { key: 'rot6', label: '6-fold (60°)', next: 'Q6', proofType: 'rotation', rotationAngleDeg: 60 },
      ],
    },
    QNR_MIRRORS: {
      id: 'QNR_MIRRORS',
      type: 'question',
      questionText: 'Mirrors?',
      answers: [
        { key: 'no', label: 'No mirrors present', next: 'QNR_GLIDES_ONLY' },
        { key: 'yes', label: 'Yes, here is a mirror', next: 'QNR_GLIDES_AFTER_MIRRORS', proofType: 'mirror' },
      ],
    },
    QNR_GLIDES_ONLY: {
      id: 'QNR_GLIDES_ONLY',
      type: 'question',
      questionText: 'Glides?',
      answers: [
        { key: 'yes', label: 'Yes, I can show a glide', next: 'CHK_GLIDES_PARALLEL', proofType: 'glide' },
        { key: 'no', label: 'No glides either', next: 'LEAF_P1' },
      ],
    },
    CHK_GLIDES_PARALLEL: {
      id: 'CHK_GLIDES_PARALLEL',
      type: 'question',
      questionText: 'Do all glides go in the SAME direction?',
      answers: [
        { key: 'yes', label: 'Yes, they are parallel', next: 'LEAF_PG', proofType: 'glide' },
        { key: 'no', label: 'No, I must have missed a rotation', next: 'GO_BACK' },
      ],
    },
    QNR_GLIDES_AFTER_MIRRORS: {
      id: 'QNR_GLIDES_AFTER_MIRRORS',
      type: 'question',
      questionText: 'Glides?',
      answers: [
        { key: 'yes', label: 'Yes, here is the glide', next: 'CHK_MIRRORS_GLIDES_PARALLEL', proofType: 'glide' },
        { key: 'no', label: 'No glides after all', next: 'CHK_MIRRORS_PARALLEL' },
      ],
    },
    CHK_MIRRORS_PARALLEL: {
      id: 'CHK_MIRRORS_PARALLEL',
      type: 'question',
      questionText: 'Do all mirrors go in the SAME direction?',
      answers: [
        { key: 'yes', label: 'Yes, they are parallel', next: 'LEAF_PM', proofType: 'mirror' },
        { key: 'no', label: 'No, this contradicts the earlier answers', next: 'GO_BACK' },
      ],
    },
    CHK_MIRRORS_GLIDES_PARALLEL: {
      id: 'CHK_MIRRORS_GLIDES_PARALLEL',
      type: 'question',
      questionText: 'Do mirrors AND glides all go in the SAME direction?',
      answers: [
        { key: 'yes', label: 'Yes, they align', next: 'LEAF_CM', proofType: 'mirror' },
        { key: 'no', label: 'No, I should search for a rotation', next: 'GO_BACK' },
      ],
    },
    GO_BACK: {
      id: 'GO_BACK',
      type: 'question',
      questionText: 'Your answers clash. Redraw your reference patch and check for rotations again.',
      answers: [{ key: 'retry', label: 'Restart rotation search', next: 'Q0' }],
    },
    // QROT removed
    Q6: {
      id: 'Q6',
      type: 'question',
      questionText: 'Mirrors?',
      answers: [
        { key: 'yes', label: 'Yes, mirrors exist', next: 'LEAF_P6MM', proofType: 'mirror' },
        { key: 'no', label: 'No mirrors', next: 'LEAF_P6' },
      ],
    },
    Q3: {
      id: 'Q3',
      type: 'question',
      questionText: 'Mirrors?',
      answers: [
        { key: 'yes', label: 'Yes, mirrors exist', next: 'Q3M', proofType: 'mirror' },
        { key: 'no', label: 'No mirrors', next: 'LEAF_P3' },
      ],
    },
    Q3M: {
      id: 'Q3M',
      type: 'question',
      questionText: 'Which diagonal of the unit cell is a mirror?',
      needsUnitCell: true,
      answers: [
        { key: 'long', label: 'Long diagonal', next: 'LEAF_P3M1', proofType: 'mirror' },
        { key: 'short', label: 'Short diagonal (and sides)', next: 'LEAF_P31M', proofType: 'mirror' },
      ],
    },
    Q4: {
      id: 'Q4',
      type: 'question',
      questionText: 'Mirrors?',
      answers: [
        { key: 'yes', label: 'Yes, here they are', next: 'Q4WHERE', proofType: 'mirror' },
        { key: 'no', label: 'No mirrors for this rotation', next: 'LEAF_P4' },
      ],
    },
    Q4WHERE: {
      id: 'Q4WHERE',
      type: 'question',
      questionText: 'Where in the unit cell are the mirrors?',
      note: [
        'Make sure the pattern at the centre of the unit cell differs from the corners.',
        'If it matches, draw a smaller centred unit cell and return to the previous step.',
      ],
      needsUnitCell: true,
      answers: [
        { key: 'axes', label: 'On sides and through centre', next: 'LEAF_P4MM', proofType: 'mirror' },
        { key: 'diagonals', label: 'At 45° through the edges', next: 'LEAF_P4GM', proofType: 'mirror' },
      ],
    },
    Q2: {
      id: 'Q2',
      type: 'question',
      questionText: 'Mirrors and/or glides?',
      answers: [
        { key: 'neither', label: 'Neither', next: 'LEAF_P2' },
        { key: 'mirrors_only', label: 'Mirrors only, both directions', next: 'Q2_MIRRORS_A' },
        { key: 'glides_only', label: 'Glides only, both directions', next: 'Q2_GLIDES_A' },
        {
          key: 'mixed',
          label: 'Mirrors in one direction, glides in the other',
          next: 'Q2_MIXED_MIRROR',
        },
        {
          key: 'both',
          label: 'Mirrors and glides going both directions',
          next: 'Q2_BOTH_MIRROR_A',
        },
      ],
    },
    Q2_MIRRORS_A: {
      id: 'Q2_MIRRORS_A',
      type: 'question',
      questionText: 'Show the first mirror direction.',
      proofType: 'mirror',
      answers: [{ key: 'done', label: 'Looks right', next: 'Q2_MIRRORS_B' }],
    },
    Q2_MIRRORS_B: {
      id: 'Q2_MIRRORS_B',
      type: 'question',
      questionText: 'Great. Now show the perpendicular mirror direction.',
      proofType: 'mirror',
      answers: [{ key: 'done', label: 'Both mirrors confirmed', next: 'LEAF_P2MM' }],
    },
    Q2_GLIDES_A: {
      id: 'Q2_GLIDES_A',
      type: 'question',
      questionText: 'Show the first glide direction.',
      proofType: 'glide',
      answers: [{ key: 'done', label: 'Looks right', next: 'Q2_GLIDES_B' }],
    },
    Q2_GLIDES_B: {
      id: 'Q2_GLIDES_B',
      type: 'question',
      questionText: 'Now show the perpendicular glide direction.',
      proofType: 'glide',
      answers: [{ key: 'done', label: 'Both glides confirmed', next: 'LEAF_P2GG' }],
    },
    Q2_MIXED_MIRROR: {
      id: 'Q2_MIXED_MIRROR',
      type: 'question',
      questionText: 'Show the mirror direction.',
      proofType: 'mirror',
      answers: [{ key: 'done', label: 'Mirror looks right', next: 'Q2_MIXED_GLIDE' }],
    },
    Q2_MIXED_GLIDE: {
      id: 'Q2_MIXED_GLIDE',
      type: 'question',
      questionText: 'Show the glide direction.',
      proofType: 'glide',
      answers: [{ key: 'done', label: 'Glide looks right', next: 'LEAF_P2MG' }],
    },
    Q2_BOTH_MIRROR_A: {
      id: 'Q2_BOTH_MIRROR_A',
      type: 'question',
      questionText: 'Show the first mirror direction.',
      proofType: 'mirror',
      answers: [{ key: 'done', label: 'Mirror recorded', next: 'Q2_BOTH_MIRROR_B' }],
    },
    Q2_BOTH_MIRROR_B: {
      id: 'Q2_BOTH_MIRROR_B',
      type: 'question',
      questionText: 'Show the perpendicular mirror direction.',
      proofType: 'mirror',
      answers: [{ key: 'done', label: 'Mirrors done', next: 'Q2_BOTH_GLIDE_A' }],
    },
    Q2_BOTH_GLIDE_A: {
      id: 'Q2_BOTH_GLIDE_A',
      type: 'question',
      questionText: 'Show the first glide direction.',
      proofType: 'glide',
      answers: [{ key: 'done', label: 'Glide recorded', next: 'Q2_BOTH_GLIDE_B' }],
    },
    Q2_BOTH_GLIDE_B: {
      id: 'Q2_BOTH_GLIDE_B',
      type: 'question',
      questionText: 'Show the perpendicular glide direction.',
      proofType: 'glide',
      answers: [{ key: 'done', label: 'All symmetries proven', next: 'LEAF_C2MM' }],
    },
    LEAF_P1: {
      id: 'LEAF_P1',
      type: 'leaf',
      groupCode: 'p1',
      description: 'Only translations — no rotations, mirrors, or glides detected.',
    },
    LEAF_PM: {
      id: 'LEAF_PM',
      type: 'leaf',
      groupCode: 'pm',
      description: 'Single family of mirror lines with pure translations otherwise.',
    },
    LEAF_PG: {
      id: 'LEAF_PG',
      type: 'leaf',
      groupCode: 'pg',
      description: 'No mirrors, but glide reflections run along a single direction.',
    },
    LEAF_CM: {
      id: 'LEAF_CM',
      type: 'leaf',
      groupCode: 'cm',
      description: 'Mirrors and glides share the same direction.',
    },
    LEAF_P6: {
      id: 'LEAF_P6',
      type: 'leaf',
      groupCode: 'p6',
      description: '6-fold rotations without mirrors.',
    },
    LEAF_P6MM: {
      id: 'LEAF_P6MM',
      type: 'leaf',
      groupCode: 'p6mm',
      description: '6-fold rotations with mirrors.',
    },
    LEAF_P3: {
      id: 'LEAF_P3',
      type: 'leaf',
      groupCode: 'p3',
      description: '3-fold rotations only.',
    },
    LEAF_P3M1: {
      id: 'LEAF_P3M1',
      type: 'leaf',
      groupCode: 'p3m1',
      description: 'Mirrors pass between the 3-fold rotation centres.',
    },
    LEAF_P31M: {
      id: 'LEAF_P31M',
      type: 'leaf',
      groupCode: 'p31m',
      description: 'Mirrors run through each 3-fold centre.',
    },
    LEAF_P4: {
      id: 'LEAF_P4',
      type: 'leaf',
      groupCode: 'p4',
      description: '4-fold rotations without mirrors or glides.',
    },
    LEAF_P4MM: {
      id: 'LEAF_P4MM',
      type: 'leaf',
      groupCode: 'p4mm',
      description: '4-fold rotations with mirrors on both axes.',
    },
    LEAF_P4GM: {
      id: 'LEAF_P4GM',
      type: 'leaf',
      groupCode: 'p4gm',
      description: 'Diagonal mirrors with glide reflections along the axes.',
    },
    LEAF_P2: {
      id: 'LEAF_P2',
      type: 'leaf',
      groupCode: 'p2',
      description: '2-fold centres without mirrors or glides.',
    },
    LEAF_P2MM: {
      id: 'LEAF_P2MM',
      type: 'leaf',
      groupCode: 'p2mm',
      description: 'Mirrors along both lattice directions.',
    },
    LEAF_P2GG: {
      id: 'LEAF_P2GG',
      type: 'leaf',
      groupCode: 'p2gg',
      description: 'Paired glides along both lattice directions.',
    },
    LEAF_P2MG: {
      id: 'LEAF_P2MG',
      type: 'leaf',
      groupCode: 'p2mg',
      description: 'Mirrors in one direction, glides in the perpendicular direction.',
    },
    LEAF_C2MM: {
      id: 'LEAF_C2MM',
      type: 'leaf',
      groupCode: 'c2mm',
      description: 'Mirrors and glides in both directions with a centred cell.',
    },
  },
};
